import Head from "next/head";
import Image from "next/image";

//icons

import { BsFillMoonStarsFill } from "react-icons/bs";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          {" "}
          @import 
          url('https://fonts.googleapis.com/css2?family=Poppins:wght@100;300;400;600;800&display=swap');{" "}
        </style>
      </Head>

        <main className="font-poppins bg-yellow-50 min-h-screen px-10">
        {/* nav and hero */}
        <section>
          {/* nav */}
          <nav className="py-10 flex justify-between">
            <h1 className="text-sm">developed by adomic arts</h1>
            <ul className="flex items-center">
              {/* icon */}
              <li>
                <BsFillMoonStarsFill
                className="cursor-pointer text-xl mx-5"/>
              </li>
              <li>
                <a href="https://drive.google.com/file/d/1WGH980EuBmviKfsUmBsh1mN3yDebwNeJ/view?usp=sharing" download={"resume"} className="bg-yellow-400 text-black px-4 py-2 border-none rounded-md">Resume</a>
              </li>
            </ul>
          </nav>

          {/* hero */}
          <div>
            <h1>Yenuli Obapitiya</h1>
            <h3>Website Developer with a Passion for Building Modern, Responsive Websites</h3>
            <p>I'm a dedicated student with a passion for website development.
               While continuing to learn and grow,
                I have developed a strong foundation in creating responsive,
                 user-friendly websites. I'm excited to take on new challenges 
                 and expand my skills through real-world projects.</p>
          </div>
          {/*social*/}
        </section>
        </main>
      </div>
  );
}
