import Head from "next/head";
import Image from "next/image";

//images

import profileImage from "../public/p2.png"

//icons

import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiOutlineGithub } from "react-icons/ai";
import { AiFillLinkedin } from "react-icons/ai";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          {" "}
          @import 
          url('https://fonts.googleapis.com/css2?family=Poppins:wght@100;300;400;600;800&display=swap');{" "}
        </style>
      </Head>

        <main className="font-poppins bg-yellow-50 min-h-screen px-10">
        {/* nav and hero */}
        <section>
          {/* nav */}
          <nav className="py-10 flex justify-between">
            <h1 className="text-sm">developed by adomic arts</h1>
            <ul className="flex items-center">
              {/* icon */}
              <li>
                <BsFillMoonStarsFill
                className="cursor-pointer text-xl mx-5"/>
              </li>
              <li>
                <a href="https://drive.google.com/file/d/1WGH980EuBmviKfsUmBsh1mN3yDebwNeJ/view?usp=sharing" download={"resume"} className="bg-yellow-400 text-black px-4 py-2 border-none rounded-md">Resume</a>
              </li>
            </ul>
          </nav>

          {/* hero */}
          <div className="text-center p-10">
            <h1 className="text-5xl font-bold text-yellow-400">Yenuli Obapitiya</h1>
            <h3 className="text-2xl py-4">Website Developer with a Passion for Building Modern, Responsive Websites</h3>
            <p className="text-sm py-4 text-gray-400 leading-6">I'm a dedicated student with a passion for website development.
               While continuing to learn and grow,
                I have developed a strong foundation in creating responsive,
                 user-friendly websites. I'm excited to take on new challenges 
                 and expand my skills through real-world projects.</p>
          </div>
          {/*social*/}
          <div className="text-5xl flex justify-center gap-16 text-gray-600">
            <a href="https://github.com/yenuliobapitiya">
              <AiOutlineGithub/>
            </a>
            <a href="https://www.linkedin.com/in/yenuli-obapitiya-93b6b92b9/">
              <AiFillLinkedin/>
            </a>
            <a href=""></a>
          </div>
          {/* profile */}
          <div className="m-auto relative bg-gradient-to-b from-yellow-200 w-80 h-80 p-5 mt-20 rounded-full">
            <Image src={profileImage} 
                   alt="profile image"  
                   layout="fill"  
                   objectFit="cover"  />
          </div>
        </section>
        </main>
      </div>
  );
}
